### ISSUE TITLE
Create icepyx demo

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/demo-gallery#11]
At AGU 2024, the a key creator of icepyx, Jessica Scheick, will be honored as a recipient of the [2024 Open Science Recognition Prize](https://www.agu.org/user-profile?cstkey=8802b318-7274-4207-ad3d-5cd2332d8d6b). Jessica is also a core member of the CryoCloud community.

As a demo, we should look at the documentation of icepyx (https://icepyx.readthedocs.io/en/latest/index.html) and wrap the examples into a Myst based site back by computation engine to allow anonymous users to interact with those examples.

**Comment by agoose77** [comment]
I started tackling this, and looked to support execution of notebooks at both build and reading time. 

I found that most of the tutorials require user input _and_ seem to be untested as a result (there are some executions that just fail). This means that build-time execution is limited to a single "demo" notebook: https://github.com/2i2c-org/demo-icepyx/blob/main/example_notebooks/QUEST_argo_data_access.md
`mystmd` needs to be updated to support disabling execution per-notebook (c.f. https://github.com/jupyter-book/mystmd/issues/1619)

We will need Thebe to support user-modifiable code cells if we want to support in-browser execution (c.f. https://github.com/search?q=repo%3Ajupyter-book%2Fmystmd+thebe&type=issues)

I will look at per-notebook execution skipping, but I think tutorial-style source editing for Thebe might not happen in time for AGU. We can discuss when James is back.

**Comment by jnywong** [comment]
Yeah, that lends weight to my comment in https://github.com/2i2c-org/demo-gallery/issues/17#issuecomment-2506551386 about preferring not to rely on `myst build --execute` when deploying a MyST site because we can't expect the content to build reliably all the time 👍

**Comment by agoose77** [comment]
Closing this as done, because all subtasks are complete.
