### ISSUE TITLE
Create sciencecore:climaterisk demo

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/demo-gallery#4]
As part of the NASA TOPS-T ScienceCore:climaterisk project, we have created a set of .ipynb notebooks that teach users how to use NASA data to understand flood and wildfire.

Create a myst version of the sciencecore:climaterisk project that is accessible as
- a static myst HTML rendered site
- a dynamic HTML site backed by Thebe (authentication via GitHub)
- magic link to launch into JupyterLab environment

**Comment by agoose77** [comment]
Closing this as done, because all subtasks are complete
